dist: trusty

language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "hhvm-3.3"
  - "hhvm-3.12"
  - "hhvm-3.18"
  - "nightly"

install:
  - composer self-update
  - composer install

script:
  - php test-load.php

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
